title: DID & VC Test Suites
url: "https://test.did.ai"

github:
  private: false
  license:
    name: Apache-2.0
  source:
    branch: "gh-pages"
    path: "/"
  repository_url: "https://github.com/transmute-industries/vc.transmute.world"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
