name: Docs

on:
  push:
    branches:
      - master

jobs:
  update-docs:
    # Don't run on any commit that features [skip ci] in the commit message
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    name: Publish documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Conformance Tests
        run: npm run test:report

      - name: Deploy report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          enable_jekyll: true
          publish_dir: ./docs
