name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        run: npm run install:ci

      - name: Lint
        run: npm run lint -- --since origin/master

      - name: Test
        run: npm run test -- --since origin/master --concurrency 1
